### ISSUE TITLE
copy edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/quick-start-guide#3]
Hi @lauraclay / @LornaLynch 
Could we get a copy edit on this resource please?
Thanks

**Comment by LornaLynch** [comment]
@MarcScott In the worksheet (right at the beginning, before the image of All the Things), there is a link to https://www.raspberrypi.org/learning/quick-start-guide/requirements/ which doesn't exist. Which file do you need this to link to instead?

**Comment by LornaLynch** [comment]
@MarcScott winscp2.png is missing from the image folder, and the link to it on the Backup document is therefore broken.

**Comment by LornaLynch** [comment]
All done apart from the issues above.

**Comment by MarcScott** [comment]
@MissPhilbin if you want to throw the files my way, I'll add them in.

**Comment by MarcScott** [comment]
I've **finally** added the image so closing this now.
